apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app.kubernetes.io/name: weather-api
    app.kubernetes.io/instance: weather-1
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: weather
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/created-by: lazerduck
spec:
  type: NodePort
  selector:
    app: weather
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30011